services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: mysql-server

  api-dock:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    container_name: api-dock
volumes:
  mysql_data:

